<?php
/**
 * Registering of custom blocks within WordPress.
 *
 * @package Abhainn
 */

namespace Abhainn\Blocks;

use Abhainn\Registerable;

/**
 * Class CustomBlocks
 */
class CustomBlocks implements Registerable {

	/**
	 * Register the custom blocks class.
	 *
	 * @return true
	 */
	public function can_register() {
		return true;
	}

	/**
	 * Handle the registering of the individual custom blocks and the handling for the render.
	 *
	 * @return void
	 */
	public function custom_blocks() {
		$base_dir = ABHAINN_PATH . 'includes/';

		$blocks = glob( ABHAINN_PATH . 'dist/blocks/**/block.json' );
		foreach ( $blocks as $block_json ) {
			$args       = [];
			$block_name = str_replace( ABHAINN_PATH . 'dist/', '', dirname( $block_json ) );

			/**
			 * We hook up with the `markup.php` file in the `includes/blocks/[name]/markup.php` directory, and not in
			 * the `dist/` folder. Therefore, we hook up our own render callback to handle it instead.
			 */
			$markup_path = sprintf( '%1$s%2$s/markup.php', $base_dir, $block_name );
			if ( ! file_exists( $markup_path ) ) {
				continue;
			}

			/**
			 * The parameters are available to all `markup.php` files.
			 *
			 * @param array     $attributes Block attributes.
			 * @param string    $content    Content within the block, such as `<InnerBlocks />`.
			 * @param \WP_Block $block      Block object and configuration.
			 *
			 * @return string
			 */
			$args['render_callback'] = function ( $attributes, $content, $block ) use ( $markup_path ) {
				ob_start();
				include $markup_path;
				$markup = ob_get_clean();

				/**
				 * Fires after the markup for the custom block has been generated. Can be used to append/prepend to the
				 * markup or for markup manipulation.
				 *
				 * @param array     $attributes Block attributes.
				 * @param string    $content Content within the block, such as `<InnerBlocks />`.
				 * @param \WP_Block $block Block object and configuration.
				 * @param string    $markup Markup generated by the custom block.
				 */
				return apply_filters( 'abhainn_custom_block_markup', $markup, $attributes, $content, $block );
			};

			/**
			 * This function will also handle the enqueuing of the following attributes:
			 *
			 * * editorScript
			 * * script
			 * * viewScript
			 * * style
			 * * viewStyle
			 */
			register_block_type_from_metadata( $block_json, $args );
		}
	}

	/**
	 * Handle actions and filters for custom Blocks.
	 *
	 * @return void
	 */
	public function register() {
		add_action( 'init', [ $this, 'custom_blocks' ] );
	}
}
